version: "3.5"
services:
  mongo-db:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    logging:
      driver: none

  example:
    image: golang:1.14-stretch
    volumes:
      - "../:/app"
    working_dir: /app
    command: sh -c "
        go mod vendor && go run examples/examples.go
      "
    depends_on:
      - mongo-db